### ISSUE TITLE
conform or react hook form

### ISSUE THREAD

**Issue by stimw** [deadcoder0904/next-14-lucia-v3-sqlite-drizzle-conform-zod-email-verification-otp-server-actions#1]
Just curious: Why did you choose Conform over React Hook Form?

I briefly looked over the documentation, and it seems like they do the same thing.

Anyway, great job!

**Comment by deadcoder0904** [comment]
because kent c dodds (i trust that guy as he worked on large scale apps like paypal) used it in his epic web dev course with remix.

i tried it in remix & liked how it worked. it made forms super-duper fast with errors handled, validation taken care of, etc...

but he also gave his reasoning like conform works with progressive enhancement so if you disable javascript, the forms will still work & you get a nice error message, etc...

i liked react-hook-form years ago but hadn't used it as i stopped writing code for a while.

now i don't think i'll use it as conform works well with remix & next.js.

i'm probably going remix way as next.js is too damn slow now & has weird patterns. remix feels fast & easy. at least for now.

try conform. you can mimic your app based on this project or kcd's workshop as the paid course still has open-source repos.

if you don't like conform, go with react-hook-form but i think both are kinda similar.

the difference is in size. [react-hook-form is huge](https://bundlephobia.com/package/react-hook-form@7.50.1) compare to [conform](https://bundlephobia.com/package/conform@0.2.16)
